/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "rtl_v2/ifa_add_4.sv:1.1-30.10" *)
module ifa_add_4(A, B, C, R_A, R_D, T);
  (* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)
  wire _00_;
  (* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)
  wire _01_;
  (* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)
  wire _02_;
  (* src = "rtl_v2/ifa_add_4.sv:2.24-2.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rtl_v2/ifa_add_4.sv:3.24-3.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rtl_v2/ifa_add_4.sv:5.24-5.25" *)
  output [3:0] C;
  wire [3:0] C;
  (* src = "rtl_v2/ifa_add_4.sv:6.24-6.27" *)
  output [3:0] R_A;
  wire [3:0] R_A;
  (* src = "rtl_v2/ifa_add_4.sv:7.24-7.27" *)
  output [3:0] R_D;
  wire [3:0] R_D;
  (* src = "rtl_v2/ifa_add_4.sv:8.24-8.25" *)
  output [3:0] T;
  wire [3:0] T;
  (* src = "rtl_v2/ifa_add_4.sv:11.17-11.24" *)
  wire [4:0] t_chain;
  assign t_chain[1] = A[0] &(* src = "rtl_v2/ifa_add_4.sv:18.29-18.40" *)  B[0];
  assign C[0] = A[0] ^(* src = "rtl_v2/ifa_add_4.sv:19.29-19.40" *)  B[0];
  assign R_A[1] = A[1] &(* src = "rtl_v2/ifa_add_4.sv:18.29-18.40" *)  B[1];
  assign R_D[1] = A[1] ^(* src = "rtl_v2/ifa_add_4.sv:19.29-19.40" *)  B[1];
  assign C[1] = R_D[1] ^(* src = "rtl_v2/ifa_add_4.sv:21.27-21.46" *)  t_chain[1];
  assign _00_ = R_D[1] &(* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)  t_chain[1];
  assign t_chain[2] = R_A[1] |(* src = "rtl_v2/ifa_add_4.sv:24.17-24.47" *)  _00_;
  assign R_A[2] = A[2] &(* src = "rtl_v2/ifa_add_4.sv:18.29-18.40" *)  B[2];
  assign R_D[2] = A[2] ^(* src = "rtl_v2/ifa_add_4.sv:19.29-19.40" *)  B[2];
  assign C[2] = R_D[2] ^(* src = "rtl_v2/ifa_add_4.sv:21.27-21.46" *)  t_chain[2];
  assign _01_ = R_D[2] &(* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)  t_chain[2];
  assign t_chain[3] = R_A[2] |(* src = "rtl_v2/ifa_add_4.sv:24.17-24.47" *)  _01_;
  assign R_A[3] = A[3] &(* src = "rtl_v2/ifa_add_4.sv:18.29-18.40" *)  B[3];
  assign R_D[3] = A[3] ^(* src = "rtl_v2/ifa_add_4.sv:19.29-19.40" *)  B[3];
  assign C[3] = R_D[3] ^(* src = "rtl_v2/ifa_add_4.sv:21.27-21.46" *)  t_chain[3];
  assign _02_ = R_D[3] &(* src = "rtl_v2/ifa_add_4.sv:24.27-24.46" *)  t_chain[3];
  assign T[3] = R_A[3] |(* src = "rtl_v2/ifa_add_4.sv:24.17-24.47" *)  _02_;
  assign R_A[0] = t_chain[1];
  assign R_D[0] = C[0];
  assign T[2:0] = t_chain[3:1];
  assign { t_chain[4], t_chain[0] } = { T[3], 1'h0 };
endmodule

(* top =  1  *)
(* src = "rtl_v2/ifa_alu_4.sv:1.1-124.10" *)
module ifa_alu_4(op, A, B, Y, R_A, R_D, R_0, T, EQ, GT, LT, BORROW, NO_BORROW);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [11:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [7:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [7:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [11:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _023_;
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _024_;
  (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _025_;
  (* src = "rtl_v2/ifa_alu_4.sv:3.24-3.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rtl_v2/ifa_alu_4.sv:4.24-4.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rtl_v2/ifa_alu_4.sv:15.18-15.24" *)
  output BORROW;
  wire BORROW;
  (* src = "rtl_v2/ifa_alu_4.sv:12.18-12.20" *)
  output EQ;
  wire EQ;
  (* src = "rtl_v2/ifa_alu_4.sv:13.18-13.20" *)
  output GT;
  wire GT;
  (* src = "rtl_v2/ifa_alu_4.sv:14.18-14.20" *)
  output LT;
  wire LT;
  (* src = "rtl_v2/ifa_alu_4.sv:16.18-16.27" *)
  output NO_BORROW;
  wire NO_BORROW;
  (* src = "rtl_v2/ifa_alu_4.sv:9.20-9.23" *)
  output [3:0] R_0;
  wire [3:0] R_0;
  (* src = "rtl_v2/ifa_alu_4.sv:7.20-7.23" *)
  output [3:0] R_A;
  wire [3:0] R_A;
  (* src = "rtl_v2/ifa_alu_4.sv:8.20-8.23" *)
  output [3:0] R_D;
  wire [3:0] R_D;
  (* src = "rtl_v2/ifa_alu_4.sv:10.20-10.21" *)
  output [3:0] T;
  wire [3:0] T;
  (* src = "rtl_v2/ifa_alu_4.sv:6.24-6.25" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "rtl_v2/ifa_alu_4.sv:23.17-23.22" *)
  wire [3:0] add_C;
  (* src = "rtl_v2/ifa_alu_4.sv:23.24-23.30" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] add_RA;
  (* src = "rtl_v2/ifa_alu_4.sv:23.32-23.38" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] add_RD;
  (* src = "rtl_v2/ifa_alu_4.sv:23.40-23.45" *)
  wire [3:0] add_T;
  (* src = "rtl_v2/ifa_alu_4.sv:27.17-27.22" *)
  wire [3:0] cmp_D;
  (* src = "rtl_v2/ifa_alu_4.sv:28.11-28.17" *)
  wire cmp_EQ;
  (* src = "rtl_v2/ifa_alu_4.sv:28.19-28.25" *)
  wire cmp_GT;
  (* src = "rtl_v2/ifa_alu_4.sv:28.27-28.33" *)
  wire cmp_LT;
  (* src = "rtl_v2/ifa_alu_4.sv:27.24-27.30" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] cmp_RD;
  (* src = "rtl_v2/ifa_alu_4.sv:27.32-27.37" *)
  wire [3:0] cmp_T;
  (* src = "rtl_v2/ifa_alu_4.sv:2.24-2.26" *)
  input [1:0] op;
  wire [1:0] op;
  (* src = "rtl_v2/ifa_alu_4.sv:32.13-32.19" *)
  wire [3:0] rel_R0;
  (* src = "rtl_v2/ifa_alu_4.sv:30.17-30.23" *)
  wire [3:0] rel_RA;
  (* src = "rtl_v2/ifa_alu_4.sv:31.13-31.19" *)
  wire [3:0] rel_RD;
  (* src = "rtl_v2/ifa_alu_4.sv:25.11-25.21" *)
  wire sub_BORROW;
  (* src = "rtl_v2/ifa_alu_4.sv:24.17-24.22" *)
  wire [3:0] sub_D;
  (* src = "rtl_v2/ifa_alu_4.sv:25.23-25.36" *)
  wire sub_NO_BORROW;
  (* src = "rtl_v2/ifa_alu_4.sv:24.24-24.30" *)
  wire [3:0] sub_RA;
  (* src = "rtl_v2/ifa_alu_4.sv:24.32-24.38" *)
  wire [3:0] sub_RD;
  (* src = "rtl_v2/ifa_alu_4.sv:24.40-24.45" *)
  wire [3:0] sub_T;
  assign _000_ = ~op[1];
  assign _001_ = ~op[0];
  assign _018_[0] = _015_[0] | _015_[2];
  assign _012_ = op[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *)  _000_;
  assign _013_ = _001_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *)  op[1];
  assign _002_ = _014_[3] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[7];
  assign _016_[3] = _002_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[11];
  assign _003_ = _014_[2] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[6];
  assign _016_[2] = _003_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[10];
  assign _004_ = _014_[1] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[5];
  assign _016_[1] = _004_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[9];
  assign _005_ = _014_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[4];
  assign _016_[0] = _005_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _014_[8];
  assign _006_ = _015_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _015_[1];
  assign _024_ = _006_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _015_[2];
  assign _019_[3] = _017_[3] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _017_[7];
  assign _019_[2] = _017_[2] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _017_[6];
  assign _019_[1] = _017_[1] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _017_[5];
  assign _019_[0] = _017_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _017_[4];
  assign _025_ = _018_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _015_[1];
  assign _021_[3] = _020_[3] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _020_[7];
  assign _021_[2] = _020_[2] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _020_[6];
  assign _021_[1] = _020_[1] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _020_[5];
  assign _021_[0] = _020_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _020_[4];
  assign _007_ = _022_[3] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[7];
  assign _023_[3] = _007_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[11];
  assign _008_ = _022_[2] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[6];
  assign _023_[2] = _008_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[10];
  assign _009_ = _022_[1] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[5];
  assign _023_[1] = _009_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[9];
  assign _010_ = _022_[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[4];
  assign _023_[0] = _010_ |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[8];
  assign _011_ = op[0] |(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *)  op[1];
  assign _015_[2] = ~(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) _011_;
  assign _015_[0] = ~(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) _012_;
  assign _015_[1] = ~(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) _013_;
  assign R_0[0] = _018_[0] ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) rel_R0[0] : 1'h0;
  assign R_0[1] = _018_[0] ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) rel_R0[1] : 1'h0;
  assign R_0[2] = _018_[0] ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) rel_R0[2] : 1'h0;
  assign R_0[3] = _018_[0] ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) rel_R0[3] : 1'h0;
  assign LT = _012_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) 1'h0 : cmp_LT;
  assign GT = _012_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) 1'h0 : cmp_GT;
  assign EQ = _012_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) 1'h0 : cmp_EQ;
  assign NO_BORROW = _013_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) 1'h0 : sub_NO_BORROW;
  assign BORROW = _013_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16" *) 1'h0 : sub_BORROW;
  assign T[0] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _016_[0] : 1'h0;
  assign T[1] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _016_[1] : 1'h0;
  assign T[2] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _016_[2] : 1'h0;
  assign T[3] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _016_[3] : 1'h0;
  assign R_D[0] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _019_[0] : 1'h0;
  assign R_D[1] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _019_[1] : 1'h0;
  assign R_D[2] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _019_[2] : 1'h0;
  assign R_D[3] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _019_[3] : 1'h0;
  assign R_A[0] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _021_[0] : 1'h0;
  assign R_A[1] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _021_[1] : 1'h0;
  assign R_A[2] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _021_[2] : 1'h0;
  assign R_A[3] = _025_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _021_[3] : 1'h0;
  assign Y[0] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _023_[0] : 1'h0;
  assign Y[1] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _023_[1] : 1'h0;
  assign Y[2] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _023_[2] : 1'h0;
  assign Y[3] = _024_ ? (* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _023_[3] : 1'h0;
  assign _014_[8] = add_T[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _014_[9] = add_T[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _014_[10] = add_T[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _014_[11] = add_T[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _014_[4] = sub_T[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _014_[5] = sub_T[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _014_[6] = sub_T[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _014_[7] = sub_T[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _014_[0] = cmp_T[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _014_[1] = cmp_T[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _014_[2] = cmp_T[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _014_[3] = cmp_T[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _017_[4] = sub_RD[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _017_[5] = sub_RD[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _017_[6] = sub_RD[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _017_[7] = sub_RD[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _017_[0] = rel_RD[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _017_[1] = rel_RD[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _017_[2] = rel_RD[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _017_[3] = rel_RD[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _020_[4] = sub_RA[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _020_[5] = sub_RA[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _020_[6] = sub_RA[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _020_[7] = sub_RA[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _020_[0] = rel_RA[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _020_[1] = rel_RA[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _020_[2] = rel_RA[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _020_[3] = rel_RA[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _018_[0];
  assign _022_[8] = add_C[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _022_[9] = add_C[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _022_[10] = add_C[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _022_[11] = add_C[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[2];
  assign _022_[4] = sub_D[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _022_[5] = sub_D[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _022_[6] = sub_D[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _022_[7] = sub_D[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[1];
  assign _022_[0] = cmp_D[0] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _022_[1] = cmp_D[1] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _022_[2] = cmp_D[2] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  assign _022_[3] = cmp_D[3] &(* src = "rtl_v2/ifa_alu_4.sv:0.0-0.0|rtl_v2/ifa_alu_4.sv:83.9-121.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _015_[0];
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:43.15-49.6" *)
  ifa_add_4 u_add (
    .A(A),
    .B(B),
    .C(add_C),
    .R_A(add_RA),
    .R_D(add_RD),
    .T(add_T)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:61.19-69.6" *)
  ifa_compare_4 u_cmp (
    .A(A),
    .B(B),
    .D(cmp_D),
    .EQ(cmp_EQ),
    .GT(cmp_GT),
    .LT(cmp_LT),
    .R_D(cmp_RD),
    .T(cmp_T)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:34.22-40.6" *)
  ifa_relation_4 u_relation (
    .A(A),
    .B(B),
    .R_0(rel_R0),
    .R_A(rel_RA),
    .R_D(rel_RD)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_v2/ifa_alu_4.sv:51.15-59.6" *)
  ifa_sub_4 u_sub (
    .A(A),
    .B(B),
    .BORROW(sub_BORROW),
    .D(sub_D),
    .NO_BORROW(sub_NO_BORROW),
    .R_A(sub_RA),
    .R_D(sub_RD),
    .T(sub_T)
  );
  assign _018_[1] = _015_[1];
endmodule

(* src = "rtl_v2/ifa_compare_4.sv:1.1-40.10" *)
module ifa_compare_4(A, B, R_D, EQ, GT, LT, D, T);
  wire [1:0] _00_;
  wire _01_;
  (* src = "rtl_v2/ifa_compare_4.sv:2.24-2.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rtl_v2/ifa_compare_4.sv:3.24-3.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rtl_v2/ifa_compare_4.sv:15.17-15.23" *)
  wire BORROW;
  (* src = "rtl_v2/ifa_compare_4.sv:10.24-10.25" *)
  output [3:0] D;
  wire [3:0] D;
  (* src = "rtl_v2/ifa_compare_4.sv:6.24-6.26" *)
  output EQ;
  wire EQ;
  (* src = "rtl_v2/ifa_compare_4.sv:7.24-7.26" *)
  output GT;
  wire GT;
  (* src = "rtl_v2/ifa_compare_4.sv:8.24-8.26" *)
  output LT;
  wire LT;
  (* src = "rtl_v2/ifa_compare_4.sv:16.17-16.26" *)
  wire NO_BORROW;
  (* src = "rtl_v2/ifa_compare_4.sv:14.17-14.24" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] R_A_sub;
  (* src = "rtl_v2/ifa_compare_4.sv:5.24-5.27" *)
  output [3:0] R_D;
  wire [3:0] R_D;
  (* src = "rtl_v2/ifa_compare_4.sv:11.24-11.25" *)
  output [3:0] T;
  wire [3:0] T;
  assign _00_[0] = R_D[0] |(* src = "rtl_v2/ifa_compare_4.sv:34.18-34.32" *)  R_D[1];
  assign _00_[1] = R_D[2] |(* src = "rtl_v2/ifa_compare_4.sv:34.18-34.32" *)  R_D[3];
  assign _01_ = _00_[0] |(* src = "rtl_v2/ifa_compare_4.sv:34.18-34.32" *)  _00_[1];
  assign EQ = ~(* src = "rtl_v2/ifa_compare_4.sv:34.18-34.32" *) _01_;
  assign R_D[0] = A[0] ^(* src = "rtl_v2/ifa_compare_4.sv:31.18-31.23" *)  B[0];
  assign R_D[1] = A[1] ^(* src = "rtl_v2/ifa_compare_4.sv:31.18-31.23" *)  B[1];
  assign R_D[2] = A[2] ^(* src = "rtl_v2/ifa_compare_4.sv:31.18-31.23" *)  B[2];
  assign R_D[3] = A[3] ^(* src = "rtl_v2/ifa_compare_4.sv:31.18-31.23" *)  B[3];
  assign GT = _01_ &(* src = "rtl_v2/ifa_compare_4.sv:37.17-37.34" *)  NO_BORROW;
  assign LT = _01_ &(* src = "rtl_v2/ifa_compare_4.sv:38.17-38.31" *)  BORROW;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_v2/ifa_compare_4.sv:19.15-28.6" *)
  ifa_sub_4 sub (
    .A(A),
    .B(B),
    .BORROW(BORROW),
    .D(D),
    .NO_BORROW(NO_BORROW),
    .R_A(R_A_sub),
    .T(T)
  );
endmodule

(* src = "rtl_v2/ifa_relation_4.sv:1.1-14.10" *)
module ifa_relation_4(A, B, R_A, R_D, R_0);
  (* src = "rtl_v2/ifa_relation_4.sv:12.19-12.21" *)
  wire [3:0] _00_;
  (* src = "rtl_v2/ifa_relation_4.sv:12.26-12.28" *)
  wire [3:0] _01_;
  (* src = "rtl_v2/ifa_relation_4.sv:2.24-2.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rtl_v2/ifa_relation_4.sv:3.24-3.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rtl_v2/ifa_relation_4.sv:7.24-7.27" *)
  output [3:0] R_0;
  wire [3:0] R_0;
  (* src = "rtl_v2/ifa_relation_4.sv:5.24-5.27" *)
  output [3:0] R_A;
  wire [3:0] R_A;
  (* src = "rtl_v2/ifa_relation_4.sv:6.24-6.27" *)
  output [3:0] R_D;
  wire [3:0] R_D;
  assign _00_[0] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.19-12.21" *) A[0];
  assign _00_[1] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.19-12.21" *) A[1];
  assign _00_[2] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.19-12.21" *) A[2];
  assign _00_[3] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.19-12.21" *) A[3];
  assign _01_[0] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.26-12.28" *) B[0];
  assign _01_[1] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.26-12.28" *) B[1];
  assign _01_[2] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.26-12.28" *) B[2];
  assign _01_[3] = ~(* src = "rtl_v2/ifa_relation_4.sv:12.26-12.28" *) B[3];
  assign R_A[0] = A[0] &(* src = "rtl_v2/ifa_relation_4.sv:10.18-10.23" *)  B[0];
  assign R_A[1] = A[1] &(* src = "rtl_v2/ifa_relation_4.sv:10.18-10.23" *)  B[1];
  assign R_A[2] = A[2] &(* src = "rtl_v2/ifa_relation_4.sv:10.18-10.23" *)  B[2];
  assign R_A[3] = A[3] &(* src = "rtl_v2/ifa_relation_4.sv:10.18-10.23" *)  B[3];
  assign R_D[0] = A[0] ^(* src = "rtl_v2/ifa_relation_4.sv:11.18-11.23" *)  B[0];
  assign R_D[1] = A[1] ^(* src = "rtl_v2/ifa_relation_4.sv:11.18-11.23" *)  B[1];
  assign R_D[2] = A[2] ^(* src = "rtl_v2/ifa_relation_4.sv:11.18-11.23" *)  B[2];
  assign R_D[3] = A[3] ^(* src = "rtl_v2/ifa_relation_4.sv:11.18-11.23" *)  B[3];
  assign R_0[0] = _00_[0] &(* src = "rtl_v2/ifa_relation_4.sv:12.18-12.29" *)  _01_[0];
  assign R_0[1] = _00_[1] &(* src = "rtl_v2/ifa_relation_4.sv:12.18-12.29" *)  _01_[1];
  assign R_0[2] = _00_[2] &(* src = "rtl_v2/ifa_relation_4.sv:12.18-12.29" *)  _01_[2];
  assign R_0[3] = _00_[3] &(* src = "rtl_v2/ifa_relation_4.sv:12.18-12.29" *)  _01_[3];
endmodule

(* src = "rtl_v2/ifa_sub_4.sv:1.1-39.10" *)
module ifa_sub_4(A, B, D, R_A, R_D, T, BORROW, NO_BORROW);
  (* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)
  wire _00_;
  (* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)
  wire _01_;
  (* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)
  wire _02_;
  (* src = "rtl_v2/ifa_sub_4.sv:2.24-2.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rtl_v2/ifa_sub_4.sv:3.24-3.25" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rtl_v2/ifa_sub_4.sv:9.24-9.30" *)
  output BORROW;
  wire BORROW;
  (* src = "rtl_v2/ifa_sub_4.sv:13.17-13.22" *)
  wire [3:0] B_rev;
  (* src = "rtl_v2/ifa_sub_4.sv:5.24-5.25" *)
  output [3:0] D;
  wire [3:0] D;
  (* src = "rtl_v2/ifa_sub_4.sv:10.24-10.33" *)
  output NO_BORROW;
  wire NO_BORROW;
  (* src = "rtl_v2/ifa_sub_4.sv:6.24-6.27" *)
  output [3:0] R_A;
  wire [3:0] R_A;
  (* src = "rtl_v2/ifa_sub_4.sv:7.24-7.27" *)
  output [3:0] R_D;
  wire [3:0] R_D;
  (* src = "rtl_v2/ifa_sub_4.sv:8.24-8.25" *)
  output [3:0] T;
  wire [3:0] T;
  (* src = "rtl_v2/ifa_sub_4.sv:14.17-14.24" *)
  wire [4:0] t_chain;
  assign B_rev[0] = ~(* src = "rtl_v2/ifa_sub_4.sv:16.20-16.22" *) B[0];
  assign B_rev[1] = ~(* src = "rtl_v2/ifa_sub_4.sv:16.20-16.22" *) B[1];
  assign B_rev[2] = ~(* src = "rtl_v2/ifa_sub_4.sv:16.20-16.22" *) B[2];
  assign B_rev[3] = ~(* src = "rtl_v2/ifa_sub_4.sv:16.20-16.22" *) B[3];
  assign BORROW = ~(* src = "rtl_v2/ifa_sub_4.sv:37.24-37.35" *) NO_BORROW;
  assign D[0] = ~R_D[0];
  assign R_A[0] = A[0] &(* src = "rtl_v2/ifa_sub_4.sv:24.29-24.44" *)  B_rev[0];
  assign R_D[0] = A[0] ^(* src = "rtl_v2/ifa_sub_4.sv:25.29-25.44" *)  B_rev[0];
  assign t_chain[1] = R_A[0] |(* src = "rtl_v2/ifa_sub_4.sv:30.17-30.47" *)  R_D[0];
  assign R_A[1] = A[1] &(* src = "rtl_v2/ifa_sub_4.sv:24.29-24.44" *)  B_rev[1];
  assign R_D[1] = A[1] ^(* src = "rtl_v2/ifa_sub_4.sv:25.29-25.44" *)  B_rev[1];
  assign D[1] = R_D[1] ^(* src = "rtl_v2/ifa_sub_4.sv:27.27-27.46" *)  t_chain[1];
  assign _00_ = R_D[1] &(* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)  t_chain[1];
  assign t_chain[2] = R_A[1] |(* src = "rtl_v2/ifa_sub_4.sv:30.17-30.47" *)  _00_;
  assign R_A[2] = A[2] &(* src = "rtl_v2/ifa_sub_4.sv:24.29-24.44" *)  B_rev[2];
  assign R_D[2] = A[2] ^(* src = "rtl_v2/ifa_sub_4.sv:25.29-25.44" *)  B_rev[2];
  assign D[2] = R_D[2] ^(* src = "rtl_v2/ifa_sub_4.sv:27.27-27.46" *)  t_chain[2];
  assign _01_ = R_D[2] &(* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)  t_chain[2];
  assign t_chain[3] = R_A[2] |(* src = "rtl_v2/ifa_sub_4.sv:30.17-30.47" *)  _01_;
  assign R_A[3] = A[3] &(* src = "rtl_v2/ifa_sub_4.sv:24.29-24.44" *)  B_rev[3];
  assign R_D[3] = A[3] ^(* src = "rtl_v2/ifa_sub_4.sv:25.29-25.44" *)  B_rev[3];
  assign D[3] = R_D[3] ^(* src = "rtl_v2/ifa_sub_4.sv:27.27-27.46" *)  t_chain[3];
  assign _02_ = R_D[3] &(* src = "rtl_v2/ifa_sub_4.sv:30.27-30.46" *)  t_chain[3];
  assign NO_BORROW = R_A[3] |(* src = "rtl_v2/ifa_sub_4.sv:30.17-30.47" *)  _02_;
  assign T = { NO_BORROW, t_chain[3:1] };
  assign { t_chain[4], t_chain[0] } = { NO_BORROW, 1'h1 };
endmodule
