`timescale 1ns/1ps

// ============================================================================
// IFÁ Processor V4.5
// YÀRÁ Native Relation Processing Element
// ============================================================================
//
// Architecture:
//
//   Binary operands
//          │
//          ├───────────────┐
//          ▼               ▼
//      Φ-P8 input       Relation channels
//          │               │
//          ▼               ▼
//    Native operation   RA / RD / R0
//          │               │
//          └───────┬───────┘
//                  ▼
//           RelationFrame
//
// The Φ-P8 channels are explicit first-class inputs. This preserves:
//
//   Binary → Φ-P8 → Relation Frame → computation
//
// until the dedicated synthesizable Φ-P8 RTL block is connected upstream.
//
// Native operations:
//
//   0 PAPO   addition
//   1 YO     subtraction
//   2 DAGBA  multiplication
//   3 PIN    integer division
//   4 KU     remainder
//   5 GBE    exponentiation
//   6 SEDA   equality
//   7 JU     greater-than
//   8 KERE   less-than
//
// Transport semantics:
//
//   T = 1 when the unrestricted result leaves the active WIDTH-bit
//       relation window.
//
//   STATE = T
//
// Division or remainder by zero produces VALID=0.
// ============================================================================

module ifa_yara_pe #(
    parameter int WIDTH         = 8,
    parameter int REL_ID_WIDTH  = 8,
    parameter int OP_WIDTH      = 4,
    parameter int VALUE_WIDTH   = 32
) (
    input  logic                     clk,
    input  logic                     rst_n,

    input  logic                     start_i,

    input  logic [REL_ID_WIDTH-1:0]  relation_id_i,
    input  logic [OP_WIDTH-1:0]      operation_i,

    input  logic [WIDTH-1:0]         operand_a_i,
    input  logic [WIDTH-1:0]         operand_b_i,

    // First-class Φ-P8 channels produced by the upstream transform.
    input  logic [WIDTH-1:0]         phi_a_i,
    input  logic [WIDTH-1:0]         phi_b_i,

    output logic                     busy_o,
    output logic                     done_o,

    output logic [REL_ID_WIDTH-1:0]  relation_id_o,
    output logic [OP_WIDTH-1:0]      operation_o,

    output logic [WIDTH-1:0]         operand_a_o,
    output logic [WIDTH-1:0]         operand_b_o,

    output logic [WIDTH-1:0]         phi_a_o,
    output logic [WIDTH-1:0]         phi_b_o,
    output logic [WIDTH-1:0]         phi_y_o,

    output logic [WIDTH-1:0]         y_o,

    output logic [WIDTH-1:0]         ra_o,
    output logic [WIDTH-1:0]         rd_o,
    output logic [WIDTH-1:0]         r0_o,

    output logic [VALUE_WIDTH-1:0]   value_o,

    output logic                     transport_o,

    output logic                     eq_o,
    output logic                     gt_o,
    output logic                     lt_o,

    output logic                     state_o,
    output logic                     valid_o
);

    localparam logic [OP_WIDTH-1:0] OP_PAPO  = 4'h0;
    localparam logic [OP_WIDTH-1:0] OP_YO    = 4'h1;
    localparam logic [OP_WIDTH-1:0] OP_DAGBA = 4'h2;
    localparam logic [OP_WIDTH-1:0] OP_PIN   = 4'h3;
    localparam logic [OP_WIDTH-1:0] OP_KU    = 4'h4;
    localparam logic [OP_WIDTH-1:0] OP_GBE   = 4'h5;
    localparam logic [OP_WIDTH-1:0] OP_SEDA  = 4'h6;
    localparam logic [OP_WIDTH-1:0] OP_JU    = 4'h7;
    localparam logic [OP_WIDTH-1:0] OP_KERE  = 4'h8;

    localparam logic [VALUE_WIDTH-1:0] MAX_WINDOW_VALUE =
        {{(VALUE_WIDTH-WIDTH){1'b0}}, {WIDTH{1'b1}}};

    logic [VALUE_WIDTH-1:0] arithmetic_value;
    logic signed [VALUE_WIDTH:0] signed_value;

    logic [WIDTH-1:0] result_y;

    // --------------------------------------------------------------------
    // Exact Φ-P8 outputs generated by hardware
    // --------------------------------------------------------------------
    logic [WIDTH-1:0] phi_a_hw;
    logic [WIDTH-1:0] phi_b_hw;
    logic [WIDTH-1:0] phi_y_hw;

    logic result_transport;
    logic result_valid;

    logic result_eq;
    logic result_gt;
    logic result_lt;

    logic [VALUE_WIDTH-1:0] power_value;

    integer power_index;

    // ------------------------------------------------------------------------
    // Exact hardware Φ-P8 transforms
    // ------------------------------------------------------------------------

    ifa_phi_p8 phi_a_transform (
        .binary_i(operand_a_i),
        .phi_o(phi_a_hw)
    );

    ifa_phi_p8 phi_b_transform (
        .binary_i(operand_b_i),
        .phi_o(phi_b_hw)
    );

    ifa_phi_p8 phi_y_transform (
        .binary_i(result_y),
        .phi_o(phi_y_hw)
    );

    // ------------------------------------------------------------------------
    // Exponentiation helper
    // ------------------------------------------------------------------------
    always_comb begin
        power_value = {{(VALUE_WIDTH-1){1'b0}}, 1'b1};

        for (
            power_index = 0;
            power_index < (1 << WIDTH);
            power_index = power_index + 1
        ) begin
            if (power_index < operand_b_i) begin
                power_value =
                    power_value
                    * {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_a_i};
            end
        end
    end

    // ------------------------------------------------------------------------
    // Native operation engine
    // ------------------------------------------------------------------------
    always_comb begin
        arithmetic_value = '0;
        signed_value     = '0;

        result_valid     = 1'b1;
        result_transport = 1'b0;

        result_eq        = (operand_a_i == operand_b_i);
        result_gt        = (operand_a_i > operand_b_i);
        result_lt        = (operand_a_i < operand_b_i);

        case (operation_i)

            OP_PAPO: begin
                arithmetic_value =
                    {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_a_i}
                    +
                    {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_b_i};

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            OP_YO: begin
                signed_value =
                    $signed(
                        {
                            1'b0,
                            {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_a_i}
                        }
                    )
                    -
                    $signed(
                        {
                            1'b0,
                            {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_b_i}
                        }
                    );

                arithmetic_value =
                    signed_value[VALUE_WIDTH-1:0];
            end

            OP_DAGBA: begin
                arithmetic_value =
                    {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_a_i}
                    *
                    {{(VALUE_WIDTH-WIDTH){1'b0}}, operand_b_i};

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            OP_PIN: begin
                if (operand_b_i == '0) begin
                    arithmetic_value = '0;
                    signed_value     = '0;
                    result_valid     = 1'b0;
                end
                else begin
                    arithmetic_value =
                        operand_a_i / operand_b_i;

                    signed_value = $signed(
                        {1'b0, arithmetic_value}
                    );
                end
            end

            OP_KU: begin
                if (operand_b_i == '0) begin
                    arithmetic_value = '0;
                    signed_value     = '0;
                    result_valid     = 1'b0;
                end
                else begin
                    arithmetic_value =
                        operand_a_i % operand_b_i;

                    signed_value = $signed(
                        {1'b0, arithmetic_value}
                    );
                end
            end

            OP_GBE: begin
                arithmetic_value = power_value;

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            OP_SEDA: begin
                arithmetic_value =
                    {{(VALUE_WIDTH-1){1'b0}}, result_eq};

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            OP_JU: begin
                arithmetic_value =
                    {{(VALUE_WIDTH-1){1'b0}}, result_gt};

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            OP_KERE: begin
                arithmetic_value =
                    {{(VALUE_WIDTH-1){1'b0}}, result_lt};

                signed_value = $signed(
                    {1'b0, arithmetic_value}
                );
            end

            default: begin
                arithmetic_value = '0;
                signed_value     = '0;
                result_valid     = 1'b0;
            end

        endcase

        result_y = arithmetic_value[WIDTH-1:0];

        if (
            signed_value < 0
            ||
            unsigned'(arithmetic_value) > unsigned'(MAX_WINDOW_VALUE)
        ) begin
            result_transport = 1'b1;
        end
        else begin
            result_transport = 1'b0;
        end

        if (!result_valid) begin
            result_transport = 1'b0;
        end
    end

    // ------------------------------------------------------------------------
    // Frame register
    // ------------------------------------------------------------------------
    //
    // One relation is accepted when start_i is asserted while not busy.
    // The result is committed on that same active edge.
    //
    // done_o pulses for one cycle.
    // ------------------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            busy_o        <= 1'b0;
            done_o        <= 1'b0;

            relation_id_o <= '0;
            operation_o   <= '0;

            operand_a_o   <= '0;
            operand_b_o   <= '0;

            phi_a_o       <= '0;
            phi_b_o       <= '0;
            phi_y_o       <= '0;

            y_o           <= '0;

            ra_o          <= '0;
            rd_o          <= '0;
            r0_o          <= '0;

            value_o       <= '0;

            transport_o   <= 1'b0;

            eq_o          <= 1'b0;
            gt_o          <= 1'b0;
            lt_o          <= 1'b0;

            state_o       <= 1'b0;
            valid_o       <= 1'b0;
        end
        else begin
            done_o <= 1'b0;
            busy_o <= 1'b0;

            if (start_i) begin
                busy_o        <= 1'b1;
                done_o        <= 1'b1;

                relation_id_o <= relation_id_i;
                operation_o   <= operation_i;

                operand_a_o   <= operand_a_i;
                operand_b_o   <= operand_b_i;

                phi_a_o       <= phi_a_hw;
                phi_b_o       <= phi_b_hw;

                // Temporary hardware boundary:
                // PHI_Y is loaded from the low WIDTH result bits until the
                // dedicated Φ-P8 RTL transform is connected.
                phi_y_o       <= phi_y_hw;

                y_o           <= result_y;

                ra_o          <= operand_a_i & operand_b_i;
                rd_o          <= operand_a_i ^ operand_b_i;
                r0_o          <= ~(operand_a_i | operand_b_i);

                value_o       <= arithmetic_value;

                transport_o   <= result_transport;

                eq_o          <= result_eq;
                gt_o          <= result_gt;
                lt_o          <= result_lt;

                state_o       <= result_transport;
                valid_o       <= result_valid;
            end
        end
    end

endmodule
